---
title: "Information choice and economic complexity"
subtitle: ""
author: "Cameron Pfiffer"
institute: "University of Oregon"
date: "October 1st, 2021"
output:
  beamer_presentation:
    keep_tex: yes
  ioslides_presentation:
    css: tufte-css-gh-pages/tufte.css
header-includes:
 - \usepackage{../cbeamer/cstyle}
 - \usepackage{booktabs}
 - \usepackage{graphicx}
 - \usepackage[labelformat=empty]{caption}
 - \usepackage{dcolumn}
 - \usepackage{anyfontsize}
 - \usepackage{adjustbox}
 - \usepackage[T1]{fontenc}
 - \usepackage{relsize}
 - \usepackage{bm}
 - \usepackage{physics}
 - \usepackage{booktabs}
 - \usepackage{longtable}
 - \usepackage{array}
 - \usepackage{multirow}
 - \usepackage{wrapfig}
 - \usepackage{float}
 - \usepackage{colortbl}
 - \usepackage{pdflscape}
 - \usepackage{tabu}
 - \usepackage{threeparttable}
 - \usepackage{threeparttablex}
 - \usepackage[normalem]{ulem}
 - \usepackage{makecell}
 - \usepackage{xcolor}
 - \usepackage{hhline}
 - \usepackage{adjustbox}
 - \usepackage{soul}
bibliography: ../references.bib
csl: ../journal-of-finance.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = F, message = F)
# library(ggplot2)
# library(tidyverse)
# library(lubridate)
# library(ggthemes)
# library(strucchange)
# library(xts)
```

```{r fig.align='center',  out.width='0.9\\paperheight'}
# magick::image_transparent(magick::image_read("table8.png"), 'white', fuzz = 0)
```

# Research question

## Research question

How should you choose what information to analyze when the economy is complicated?

Alternatively, how much information is it \blue{rational to ignore}?

## 